### ISSUE TITLE
the  Conv layer is 1D or 2D??

### ISSUE THREAD

**Issue by ghost** [NervanaSystems/deepspeech#9]
the  Conv layer is 1D or 2D??

in train.py ,,conv layer is 1D or 2D?

i see it is 1D conv layer,,,is right?

**Comment by tyler-nervana** [comment]
We use a 1D convolution over a mel-frequency spectrogram in `train.py` because, for us, it gave similar results to a 2D convolution over a linear spectrogram but with significantly less computational overhead.

**Comment by ghost** [comment]
@tyler-nervana ,i use pdb find: the conv layer,inputshape is (1,13,2998),and output is (1152,1,1000)

the input shape is one vedio ,but the batchsize is 32,,,
Is it a convolution of a vedio do　frop?????

**Comment by tyler-nervana** [comment]
I'm not sure I fully understand your question, so please do try to clarify if I miss the point. You are correct that the input is 1 channel, 13 frequency bands and 2998 timesteps. We do a 1-D convolution, in that our filter collapses across the frequency dimension while convolving along the temporal dimension. Since we have a temporal stride of 3, this reduces the number of timesteps to 1000. We use 1152 of these filters in the convolutional layer of `train.py`. This is where the output shape of `(1152, 1, 1000)` comes from. The batch size of 32 is not included in the `in_shape` or `out_shape` parameters of the layer.
